### ISSUE TITLE
ModuleNotFoundError: No module named 'playground'

### ISSUE THREAD

**Issue by AlexanderBabel** [v411e/hasswebhookbot#1]
When trying to create an instance, the creation fails with the following error:

```
15:02:09	ERROR	server	Traceback (most recent call last):
  File "/opt/maubot/maubot/loader/zip.py", line 203, in _load
    importer.load_module(module)
  File "/opt/maubot/maubot/lib/zipimport.py", line 282, in load_module
    exec(code, mod.__dict__)
  File "/data/plugins/com.valentinriess.hasswebhook-v0.0.8.mbp/hasswebhook.py", line 10, in <module>
    from playground.hasswebhookbot.config import Config
ModuleNotFoundError: No module named 'playground'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/maubot/maubot/management/api/middleware.py", line 48, in error
    return await handler(request)
  File "/opt/maubot/maubot/management/api/instance.py", line 87, in update_instance
    return await _update_instance(instance, data)
  File "/opt/maubot/maubot/management/api/instance.py", line 71, in _update_instance
    await instance.update_started(data.get("started", None))
  File "/opt/maubot/maubot/instance.py", line 289, in update_started
    await (self.start() if started else self.stop())
  File "/opt/maubot/maubot/instance.py", line 173, in start
    cls = await self.loader.load()
  File "/opt/maubot/maubot/loader/zip.py", line 188, in load
    return self._load(reset_cache)
  File "/opt/maubot/maubot/loader/zip.py", line 207, in _load
    raise MaubotZipLoadError(f"Failed to load module {module}")
maubot.loader.zip.MaubotZipLoadError: Failed to load module hasswebhook
```

**Comment by AlexanderBabel** [comment]
Fixed in #2
